backend:
  name: github
  repo: SnackeyesBoy/Snackeyes.blog
  branch: main
  base_url: https://decap-cms-oauth-provider.vercel.app
  auth_endpoint: /api/auth
  client_id: "Ov23liE90vVa4boGmCcT"

media_folder: "static/img"
public_folder: "/img"

collections:
  - name: "blog" 
    label: "部落格文章"
    folder: "content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "標題", name: "title", widget: "string" }
      - { label: "發布日期", name: "date", widget: "datetime" }
      - { label: "是否為草稿", name: "draft", widget: "boolean", default: false }
      - { label: "版面配置", name: "layout", widget: "hidden", default: "single" }
      - { label: "大類別 (Categories)", name: "categories", widget: "list" }
      - { label: "標籤 (Tags)", name: "tags", widget: "list" }
      - { label: "文章內文", name: "body", widget: "markdown" }

  - name: "works"
    label: "作品列"
    folder: "content/works"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "作品名稱", name: "title", widget: "string" }
      - { label: "日期", name: "date", widget: "datetime" }
      - { label: "是否為草稿", name: "draft", widget: "boolean", default: false }
      - { label: "文章內文", name: "body", widget: "markdown" }