backend:
  name: github
  repo: SnackeyesBoy/Snackeyes.blog
  branch: main
  base_url: https://api.sveltia.org
  auth_endpoint: /auth
  client_id: "Ov23liE90vVa4boGmCcT"
  # auth_type: implicit # 如果 api.sveltia.org 還是連不上，再把這行與下面那行解開
  # local_backend: true

media_folder: "static/img"
public_folder: "/img"

collections:
  # ==========================================
  # 1. 部落格文章分類 (blog)
  # ==========================================
  - name: "blog" 
    label: "部落格文章"
    folder: "content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "標題", name: "title", widget: "string" }
      - { label: "發布日期", name: "date", widget: "datetime" }
      - { label: "是否為草稿", name: "draft", widget: "boolean", default: false }
      - { label: "版面配置", name: "layout", widget: "hidden", default: "single" }
      - { label: "文章封面縮圖", name: "image", widget: "image", required: false, default: "" }
      
      - name: "categories"
        label: "大類別 (Categories)"
        widget: "list"
        summary: "{{fields.category}}"
        field: { label: "分類名稱", name: "category", widget: "string" }
        
      - name: "tags"
        label: "標籤 (Tags)"
        widget: "list"
        summary: "{{fields.tag}}"
        field: { label: "標籤名稱", name: "tag", widget: "string" }

      - { label: "文章內文", name: "body", widget: "markdown" }

  # ==========================================
  # 2. 作品列分類 (works) 
  # ==========================================
  - name: "works"
    label: "作品列"
    folder: "content/works"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "標題", name: "title", widget: "string" }
      - { label: "發布日期", name: "date", widget: "datetime" }
      - { label: "是否為草稿", name: "draft", widget: "boolean", default: false }
      - { label: "版面配置", name: "layout", widget: "hidden", default: "single" }
      - { label: "文章封面縮圖", name: "image", widget: "image", required: false, default: "" }
      
      - name: "categories"
        label: "大類別 (Categories)"
        widget: "list"
        summary: "{{fields.category}}"
        field: { label: "分類名稱", name: "category", widget: "string" }
        
      - name: "tags"
        label: "標籤 (Tags)"
        widget: "list"
        summary: "{{fields.tag}}"
        field: { label: "標籤名稱", name: "tag", widget: "string" }

      - { label: "文章內文", name: "body", widget: "markdown" }